# Generated by Django 5.1.5 on 2025-02-06 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Software Developer', 'Software Developer'), ('IT Support', 'IT Support'), ('Call Agent', 'Call Agent'), ('Supervisor', 'Supervisor')], max_length=50)),
                ('tin_number', models.CharField(max_length=20, unique=True)),
                ('employment_date', models.DateField(default=django.utils.timezone.now)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('misconduct', models.IntegerField(default=0)),
                ('call_flow_input', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aht_input', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pickup_input', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impv_input', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_date', models.DateField(default=django.utils.timezone.now)),
                ('scheduled_working_days_input', models.IntegerField(default=30)),
                ('working_day_adjustment', models.IntegerField(default=0)),
                ('work_days', models.IntegerField(default=0)),
                ('sunday', models.IntegerField(default=0)),
                ('holiday', models.IntegerField(default=0)),
                ('justified', models.IntegerField(default=0)),
                ('unjustified', models.IntegerField(default=0)),
                ('tardiness_l', models.IntegerField(default=0)),
                ('tardiness_vl', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
    ]
